import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "../../Context/Authcontext";
import NavBar from "./Component/NavBar/NavBar/NavBar";
import { ImageProvider } from "../../Context/Valuecontex";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <AuthProvider>
          <ImageProvider>
            {children}
          </ImageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
